---
_extends: .github

repository:
  name: hs-msgpack-types
  description: Abstract data types and type classes for Haskell to MessagePack value converters
  topics: msgpack, haskell
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "bazel-opt"
          - "build / cabal"
          - "build / stack"
