---
language: generic
dist: xenial
os: linux

env:
  global:
    # HACKAGE_USERNAME=[secure]
    - secure: "jicOwfg/YO+V/SOew9Ui4YKsYECZQD9noMq4rN5SHrQjTDvDEZE92US01Xw09YOfQe+BCRWiy18i9GThWeXAJHXZh06c1e/KjDLnMWWqgt4QSmepSRdN2ImYF/I3t7aG2Zp3QYCrqFjq66hUw/danQqUIpMpJ3M7IVyF/U5eq/U+BV243o5BDnaEZDLRbwWsFAN7Y4UX5n3aFoaTBYyU4gkRUmTSkU19QV4pW9izhnA8AyqPWqUZyqTOQOnmDPLC4j51vzEnduzv7kfv4l/AYk87hw96KVySo+Hvd2841GaoFHAgok0CS+sbmzrUjnmHsVBqlslNpro7FMo0FnUnLdV/dnssjsMt/FtVaeKacWD1jf2WFKLAFoEJzgrb8LIpUvYiSHjYOP5vY8a0/6nEDM6pE3/YasSCD0j6uWZfA4G3JmNSi4cqKzCz/panQbZxAxj75M61vDcP5BnAtTVd5yJ7aQSXjEMOWTYLWgf6JdzzjJCia/YMzmconjmF5enKuv5RZfasQoHhhP4ZHlojcEYCH+G3oM4oL7NNIQLpk27yF4vS340jHUJSKoYsM2ysTx2dTnyd97fhfAPwzwI3ZQRHMZK1GcDpv+K42Xu1DkXcIqADJEkhZirTuLV6kNC0OZlxwrYmqE6qvYWMhpvRgG2dmppEV9/GgAY0jnYQkkU="
    # HACKAGE_PASSWORD=[secure]
    - secure: "cTGxbP7X5pvMsvvrH960NOnLyL6H8zp/v7Vl0EI3s9pKEWfgcbNnkH8r5q/dO7MOpei6qqzwO+WCZGxGQRaISXydKyf8d3HriWlyAzg0PS1GMmpYdWkAoP3c/6K4BB09AXuiAnAwRxMYbrbJyGATA9zwqNB7UjaxMVMMb8Q9r+Ulm5o5lmOc37gqxRa7w+4MB6ayw5xSJC6+S2y56cocc4GKUeJaBU1xrsZevCHKtEgu8xoRgo/2gP0G8qCZDPTuHe7/iD+dXyNsNUtMKHZE3U5RSh2SvLtjRIjRkBgOICPYr/BgCX1303NOln85ZQeshf4KYulgsk4s5pqZ1dmuiz+gR97qKxulCLP5jTGRFHM3QfSutAcE40spXkc7Q62kLKBMcWFAQWo4DY9zW48ifEvhekYbqe5T5X6pzli06sWp7kqZThBQV3AmiZeHldiPiwnlXFPr4yzqnjZvoMgaSzMSwsNz94Kxr7Pr4hspwko/pe30sJktbdWP5fJnBoLKL7WNQlqtNfgFacyxnpjQXcIsrtopDbTmUKFb7URshfOuy7zQJybVSfFFgHXqWhUgn09BBxGcR29l8mf/NEO7RWb776w+KkZhw6/lMt68lZXoJsnDOFN3EsVWt5eok2RuJ4xxvnst2ogP2JMVL1IpBQfr8uiE9TBhtNgJCicCQfA="

cache:
  timeout: 600
  directories:
    - $HOME/.local
    - $HOME/.stack

script:
  - bash <(travis_retry curl -s https://raw.githubusercontent.com/TokTok/hs-tools/master/bin/travis-haskell) script
  - eval $(travis-haskell env)

deploy:
  provider: releases
  token:
    secure: "GETDyyKHg5qRIICJGLMEGjxqajLDkFHg176fNgxc+M2+6X45a9afutBR3yqMTbDxQG1N11aNJII10JX3YxPAl9UKCwiPOB/24VXpE5EA0BzT1T3XIkQK4y4+JAj6syf55xWxnh98r7KMwmchU7e/7zTUR7kJgndNc0CjYq19WowjOjX21SeGznb+MnefbYzBI+vjmNvZNlgi62BSJ4BidLXNnfnQbL+enebptWi8naFdF3A5+5rMMQ0c5pkJm3QBOK1JIphhYFWDH9QHpPO9kR8HVwV32ArMxxe5moznssHW9/SFnmaMXJn+t4N+57cCXEFrtBovIxf/Zxtk9kvRkzf0iC0Bpo5mHMCVZ4Yd0IliUg+VszUa0LO/DOJutn9U3HcG1JcD5B3Mb8pdGwcb7/hRKI6gvwmb/YyJa2AIeiI3eXHCouWXtBM9Y0b/eSVmlJC+EpVMTaDtro7raX+UWwme470EiQ21cTXmwGOIrD4+/ooYOYKu7PaO0Ti6xsHuW0cAl0KF5O2y3wiCkU1i0aBt3xo96Brthar3MsGCplCX8JK0kNQr6iq1WkeDAVkJkek95ylG/udbbrfa6lStzoa7mzdq1OktafmCVoe0P4WCWf6VBQvTSRZVIHhjp8wIbYSP4MNIxLR+eguyjX0+6Z1UFBY68vIRRvRqX/6dKpg="
  file: $PACKAGE-$VERSION.tar.gz
  skip_cleanup: true
  on:
    repo: TokTok/hs-msgpack-types
    tags: true

after_deploy: travis-haskell deploy

# Only build pull requests and releases, don't build master on pushes,
# except through api or cron.
if: type IN (pull_request, api, cron) OR tag IS present
