---
cache:
  - '%APPDATA%\cabal'
  - '%APPDATA%\ghc'

install:
  - choco install ghc --version 8.2.2
  - refreshenv

build_script:
  - cabal update
  - cabal install happy --overwrite-policy=always
  - cabal configure --enable-tests --enable-benchmarks
  - cabal build

test_script:
  - cabal test
