---
cache:
  - '%APPDATA%\cabal'
  - '%APPDATA%\ghc'

install:
  - choco install ghc --version 8.2.2
  - refreshenv

build_script:
  - cabal update
  - cabal install happy
  - cabal install --enable-tests --enable-benchmarks --disable-documentation --only-dependencies

test_script:
  - cabal test
